// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5638.shiftyTenk;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.TalonSRX;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
//import com.ctre.MotorControl.SmartMotorController;
import com.ctre.phoenix.motorcontrol.FeedbackDevice;
//import com.ctre.MotorControl.SmartMotorController.FeedbackDevice;
//import com.ctre.MotorControl.SmartMotorController.TalonControlMode;
import com.ctre.phoenix.motorcontrol.ControlMode;


import org.usfirst.frc5638.shiftyTenk.subsystems.driveTrain;

//import com.ctre.Mechanical.Gearbox;
//import com.ctre.phoenix.mechanical.Gearbox;
 //import com.ctre.Mechanical.SensoredGearbox;
//import com.ctre.phoenix.drive.SensoredDriveMode;
//import com.ctre.Drive.ISmartDrivetrain;
//import com.ctre.Drive.SensoredTank;
//import com.ctre.phoenix.drive.DiffDrive;

import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.RobotDrive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    public static FeedbackDevice leftfeed;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX driveTrainleft;
    public static WPI_TalonSRX driveTrainleft1;
    public static WPI_TalonSRX driveTrainright;
    public static WPI_TalonSRX driveTrainright1;
    public static RobotDrive driveTrainrobotDrive;
    public static DoubleSolenoid shiftSubshiftSol;
    //public static TalonSRX left;
   // public static TalonSRX right;
    //public static Gearbox left;
    //public static Gearbox right;
    //public static DiffDrive driveTrain;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainleft = new WPI_TalonSRX(3);
        driveTrainleft.configSelectedFeedbackSensor(FeedbackDevice.CTRE_MagEncoder_Relative, 0, 10);
        
        driveTrainleft1 = new WPI_TalonSRX(4);
        driveTrainleft1.set(ControlMode.Follower, 3);
        
        driveTrainright = new WPI_TalonSRX(2);
        driveTrainright.configSelectedFeedbackSensor(FeedbackDevice.CTRE_MagEncoder_Relative, 0, 10);
        
        driveTrainright1 = new WPI_TalonSRX(5);
        driveTrainright1.set(ControlMode.Follower, 2);
        
        
        //left = new SensoredGearbox(4096, driveTrainleft, null);
        //right = new SensoredGearbox(4096, driveTrainright, null);
        
        
        
        //left.SetVoltageRampRate(6);
        //right.SetVoltageRampRate(6);
        
        //driveTrain = new SensoredTank(left, right, false, false, 2, 0);
        driveTrainrobotDrive = new RobotDrive(driveTrainleft, driveTrainleft1, driveTrainright, driveTrainright1);
        /*
        driveTrainrobotDrive.setSafetyEnabled(true);
        driveTrainrobotDrive.setExpiration(0.1);
        driveTrainrobotDrive.setSensitivity(0.5);
        driveTrainrobotDrive.setMaxOutput(1.0);
		*/
        shiftSubshiftSol = new DoubleSolenoid(0, 0, 1);
        LiveWindow.addActuator("shiftSub", "shiftSol", shiftSubshiftSol);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
